################################################################################
# Name: playbook_install_openstack.yml
# Description:
#  - Ansible playbookt to install openstack on
#    a single node (controller node) Ubuntu
# Usage: ansible-playbook playbook_install_openstack.yml -i inventory
# Doc: https://docs.openstack.org/devstack/latest/guides/single-machine.html
# Author: Christophe Rime
# Date: 2021-03-10
# Version: 0.1
# Repo: https://github.com/christopherime/openstack-ansible-playbook
# License: MIT
################################################################################
- name: install openstack
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
  # sudo useradd -s /bin/bash -d /opt/stack -m stack
  - name: create stack user
    user:
      name: stack
      shell: /bin/bash
      home: /opt/stack
      createhome: yes
      state: present
  # sudo chmod +x /opt/stack
  - name: change stack user permission /opt/stack 
    file:
      path: /opt/stack
      mode: 0755
      state: directory
  # apt-get install sudo -y || yum install -y sudo
  # - name: install sudo
  #   apt:
  #     name: sudo
  #     state: present
  #     update_cache: yes
  # I will not install sudo because it is already installed
  # it's Ubuntu... sudo is installed by default

  # echo "stack ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/stack
  - name: add stack user to sudoers
    lineinfile:
      path: /etc/sudoers.d/stack
      line: 'stack ALL=(ALL) NOPASSWD: ALL'
      state: present
      create: yes
      #mode: 0440 # not sure for 0440, copilot suggested it to me
  
  # sudo apt-get install git -y || sudo yum install -y git
  # - name: install git
  #   apt:
  #     name: git
  #     state: present
  #     update_cache: yes
  # I will not install git because it is already installed
  # on Ubuntu nowadays (22.04) and this should be done way 
  # earlier in the process, like it's a prerequisite..

  # git clone https://opendev.org/openstack/devstack
  # copilot suggested to dest /opt/stack/devstack
  # I will stick to the guide and clone in ~ 
  # for user 'stack'
  - name: clone devstack
    git:
      repo: https://opendev.org/openstack/devstack
      dest: /home/stack/devstack
      version: master

  